version: 2

sources:
  - name: bondara_raw
    database: bondara
    schema: raw
    description: "Latest raw data snapshots from Bondara source systems."

    tables:
      - name: ing_customers
        description: "Current-state snapshot of customers, loaded from customers.csv."
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 30, period: hour}
        loaded_at_field: snapshot_ingested_at
      - name: ing_loan_applications
        description: "Current-state snapshot of loan applications, loaded from LoanApplications.csv."
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 30, period: hour}
        loaded_at_field: snapshot_ingested_at
      - name: ing_loans
        description: "Current-state snapshot of loans, loaded from loans.csv."
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 30, period: hour}
        loaded_at_field: snapshot_ingested_at
      - name: ing_repayments
        description: "Append-only log of daily loan repayment events, loaded from repayments.csv."
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 30, period: hour}
        loaded_at_field: snapshot_ingested_at
      - name: ing_countries
        description: "Country lookup table loaded from countries.json."
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 30, period: hour}
        loaded_at_field: snapshot_ingested_at
      - name: ing_loan_product_types
        description: "Loan product type lookup table loaded from loan_product.csv."
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 30, period: hour}
        loaded_at_field: snapshot_ingested_at